services:
  eventhub:
    container_name: eventhub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.local
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    command: redis-server --save "" --appendonly no