spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DB}

spring.mongodb.database=${MONGODB_DATABASE}
spring.mongodb.host=${MONGODB_HOST}
spring.mongodb.port=${MONGODB_PORT}
spring.mongodb.username=${MONGODB_USER}
spring.mongodb.password=${MONGODB_PASSWORD}
spring.mongodb.authentication-database=${MONGODB_DATABASE}
spring.data.mongodb.auto-index-creation=true

server.port=${APP_PORT:8080}
server.address=${APP_HOST:0.0.0.0}