spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DB}

spring.mongodb.database=${MONGODB_DATABASE}
spring.mongodb.host=${MONGODB_HOST}
spring.mongodb.port=${MONGODB_PORT}
spring.mongodb.username=${MONGODB_USER}
spring.mongodb.password=${MONGODB_PASSWORD}
spring.mongodb.authentication-database=${MONGODB_DATABASE}
spring.data.mongodb.auto-index-creation=true

server.port=${APP_PORT:8080}
server.address=${APP_HOST:0.0.0.0}

spring.cassandra.contact-points=${CASSANDRA_HOSTS}
spring.cassandra.port=${CASSANDRA_PORT}
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE}
spring.cassandra.local-datacenter=dc1
spring.cassandra.request.consistency=${CASSANDRA_CONSISTENCY}

app.likeTtl=${APP_LIKE_TTL}
app.eventReviewsTtl=${APP_EVENT_REVIEWS_TTL}

app.neo4j.url=${NEO4J_URL}
app.neo4j.user=${NEO4J_USERNAME:}
app.neo4j.password=${NEO4J_PASSWORD:}
app.recommendations.ttl=${APP_RECOMMENDATIONS_TTL}